name: Log Groups

on:
  push:
  workflow_dispatch:

jobs:
  loggroups:
    runs-on: ubuntu-latest
    steps:
    - shell: pwsh
      run: |
        Write-Host -Object '::group::1'
        1..52 | % {
          Write-Host -Object ('This is line number {0}' -f $PSitem)
          if (($PSitem % 5) -eq 0) {
            Write-Host -Object '::endgroup::'
            Write-Host -Object ('::group::{0}' -f ($PSItem + 1))
        }
        Write-Host -Object '::endgroup::'

