name: Log Groups

on:
  push:
  workflow_dispatch:

jobs:
  loggroups:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo '::group::My Application'
        echo 'Here is a log message'
        echo 'aweawehjwj is a log message'
        echo 'asdfHere is a log message'
        echo '::endgroup::'
    
