name: Mask Value

env:
  PHRASE: Fido the dog

on:
  push:
  workflow_dispatch:

jobs:
  maskvalue:
    runs-on: ubuntu-latest
    steps:
    - shell: pwsh
      run: |
        Write-Host -Object ('::add-mask::{0}' -f $env:PHRASE)
    - shell: pwsh
      run: |
        Write-Host -Object 'Fido the dog is my friend'
